@ZM.Users.Api_HostAddress = http://localhost:5064

GET {{ZM.Users.Api_HostAddress}}/api/users
Accept: application/json

###

GET {{ZM.Users.Api_HostAddress}}/api/users/11111111-1111-1111-1111-111111111111
Accept: application/json

###
